### PR TITLE
Fixes v2

### PR DESCRIPTION
**Pull request by hdante**

### CODE REVIEW

**Comment by MarkRivers** [comment]
Why did you remove medipix_low.c and medipix_test.c?  Couldn't those be useful in the future?  As long as they are commented out of the Makefile are they hurting anything?

**Comment by hdante** [comment]
They are unused currently. They might be useful in the future, and are stored in the repository history.

**Comment by MarkRivers** [comment]
I see no reason to delete them.  One would have to know that they used to exist to know that they are in the repository history.  I commonly leave test files in my repositories, which are a useful reminder of problems that once occurred and might come back again at some future date.

**Comment by MarkRivers** [comment]
This was superseded by #8 .

**Pull request closed without merging**
